linker:	linker.c
	gcc linker.c -o linker

clean:
	rm linker

# Run Linker on files with main first.
#
# ./linker main1.o myadd.o
# or
# ./linker -o main1.o myadd.o
#
# Redirect output to file like this
#
# ./linker main1.o myadd.o > result.o
#